### ISSUE TITLE
The logic of your js code

### ISSUE THREAD

**Issue by shiryz** [WebAhead6/Taskinator#1]
Your code seems to be working but missing a lot of logic.

- Why add icons for delete if you won't use them?

- Your code isn't clean - delete all the comments and all the unused code
  - You have a lot of unused code because the code is incomplete

- For a 2 day project, you can do a lot more! 92 lines of code that only add tasks is not enough

- It is apparent you have not tested your code, you have 2 minimal tests...

**Comment by baderfahoum17** [comment]
all logic is fixed now

cleaned the code

added more logic to the project

added more tests
